name: Build Release

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
      - run: msbuild jobba.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release
      - uses: actions/upload-artifact@v3
        with:
          name: jobba.exe
          path: ./**/jobba.exe
          retention-days: 1
